export let config={
 metrika:{name:64365469},
 ls:{
  name:'ls-vid'
 },
 'index':{
  preload:{
   '1':{
    /*'images/':{imgs:['question-photo.png','map-bg2.png']},
    'images/packing/':{j:[12,8,5],tmpl:['packing-[i]-[j].png','packing-[i]-[j]-p.png']}*/
   }
  }
 },
 'timer':{
  //url:'timer.php?time='
 },
 board:{//rename and redo
  url:'php.php?board='
 },
 sound:{
  template:'<audio src="../sounds/<%= src %>.mp3" preload="auto" <%= loop?"loop":"" %>></audio>'
 },
 /*redirect:{//needed?
   '1':'end.php'
  },*/
 'player':{
  quality:[
   {
    width:'(min-width:1281px)',
    label:'720P'
   },
   {
    width:'(max-width:1280px)',
    label:'360P'
   }
  ],
  data:{
   '1':[//[noAutoClose:true|repeatable:true|delayedPause:-1|noVidAutoPlay:true|]checkpoint:true|iniTimer:true
    {
     base:{
      src:['../videos/1-start.mp4','../videos/1-start.mp4'],
      timecodes:[{start:0.5,invoked:false,data:{interactive:'Start'}}],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:['../videos/1-1-yes.mp4','../videos/1-1-yes.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/1-2-no.mp4','../videos/1-2-no.mp4'],rewind:'../videos/1-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/2-start.mp4','../videos/2-start.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/2-3-check.mp4','../videos/2-3-check.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/2-1-boom.mp4','../videos/2-1-boom.mp4'],rewind:'../videos/2-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/2-2-no.mp4','../videos/2-2-no.mp4'],rewind:'../videos/2-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/2-int.mp4','../videos/2-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/2-3-1-why.mp4','../videos/2-3-1-why.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/2-1-boom.mp4','../videos/2-1-boom.mp4'],rewind:'../videos/2-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/2-2-no.mp4','../videos/2-2-no.mp4'],rewind:'../videos/2-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/2-int.mp4','../videos/2-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/2-3-2-howwlong.mp4','../videos/2-3-2-howwlong.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/2-1-boom.mp4','../videos/2-1-boom.mp4'],rewind:'../videos/2-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/2-2-no.mp4','../videos/2-2-no.mp4'],rewind:'../videos/2-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/2-int.mp4','../videos/2-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/2-3-3-permit.mp4','../videos/2-3-3-permit.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/2-1-boom.mp4','../videos/2-1-boom.mp4'],rewind:'../videos/2-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/2-2-no.mp4','../videos/2-2-no.mp4'],rewind:'../videos/2-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/2-int.mp4','../videos/2-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:['../videos/2-1-boom.mp4','../videos/2-1-boom.mp4'],rewind:'../videos/2-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/2-3-3-1-late.mp4','../videos/2-3-3-1-late.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/4-start.mp4','../videos/4-start.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:['../videos/4-1-fine.mp4','../videos/4-1-fine.mp4'],rewind:'../videos/4-1-fine-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/4-2-no.mp4','../videos/4-2-no.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/6-start.mp4','../videos/6-start.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/6-why.mp4','../videos/6-why.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/6-1-fine.mp4','../videos/6-1-fine.mp4'],rewind:'../videos/6-1-fine-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/6-2-no.mp4','../videos/6-2-no.mp4'],rewind:'../videos/6-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/6-int.mp4','../videos/6-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/6-howlong.mp4','../videos/6-howlong.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/6-1-fine.mp4','../videos/6-1-fine.mp4'],rewind:'../videos/6-1-fine-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/6-2-no.mp4','../videos/6-2-no.mp4'],rewind:'../videos/6-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/6-int.mp4','../videos/6-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:['../videos/6-yes.mp4','../videos/6-yes.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/6-2-no.mp4','../videos/6-2-no.mp4'],rewind:'../videos/6-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/7-start.mp4','../videos/7-start.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/7-3-why.mp4','../videos/7-3-why.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/7-1-boom.mp4','../videos/7-1-boom.mp4'],rewind:'../videos/7-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/7-2-no.mp4','../videos/7-2-no.mp4'],rewind:'../videos/7-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/7-int.mp4','../videos/7-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:['../videos/7-3-3-docs.mp4','../videos/7-3-3-docs.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:['../videos/7-1-boom.mp4','../videos/7-1-boom.mp4'],rewind:'../videos/7-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/7-3-2-no.mp4','../videos/7-3-2-no.mp4'],rewind:'../videos/7-2-no-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:['../videos/7-int.mp4','../videos/7-int.mp4'],
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:['../videos/7-3-3-1-boom.mp4','../videos/7-3-3-1-boom.mp4'],rewind:'../videos/7-3-3-1-boom-rev.mp4',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:['../videos/7-3-3-2-no.mp4','../videos/7-3-3-2-no.mp4'],data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    }
   ]
  }
 },
 interactives:{

 }
};