export let config={
 metrika:{name:64365469},
 ls:{
  name:'ls-vid'
 },
 'index':{
  preload:{
   '1':{
    /*'images/':{imgs:['question-photo.png','map-bg2.png']},
    'images/packing/':{j:[12,8,5],tmpl:['packing-[i]-[j].png','packing-[i]-[j]-p.png']}*/
   }
  }
 },
 'timer':{
  //url:'timer.php?time='
 },
 board:{//rename and redo
  url:'php.php?board='
 },
 sound:{
  template:'<audio src="../sounds/<%= src %>.mp3" preload="auto" <%= loop?"loop":"" %>></audio>'
 },
 /*redirect:{//needed?
   '1':'end.php'
  },*/
 'player':{
  quality:[
   {
    width:'(min-width:1600px)',
    label:'1080P'
   },
   {
    width:'(min-width:1280px) and (max-width:1599px)',
    label:'720P'
   },
   {
    width:'(max-width:1279px)',
    label:'360P'
   }
  ],
  srcData:{
   spec:['1080','720','360'],
   tmpl:'../videos/<%= spec %>/<%= src %>.mp4'
  },
  data:{
   '1':[//[noAutoClose:true|repeatable:true|delayedPause:-1|noVidAutoPlay:true|]checkpoint:true|iniTimer:true
    {
     base:{
      src:'1-start',
      timecodes:[{start:0.5,invoked:false,data:{interactive:'Start'}}],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:'1-1-yes',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'1-2-no',rewind:'1-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'2-start',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'2-3-check',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'2-1-boom',rewind:'2-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'2-2-no',rewind:'2-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'2-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'2-3-1-why',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'2-1-boom',rewind:'2-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'2-2-no',rewind:'2-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'2-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'2-3-2-howwlong',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'2-1-boom',rewind:'2-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'2-2-no',rewind:'2-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'2-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'2-3-3-permit',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'2-1-boom',rewind:'2-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'2-2-no',rewind:'2-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'2-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:'2-1-boom',rewind:'2-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'2-3-3-1-late',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'4-start',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:'4-1-fine',rewind:'4-1-fine-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'4-2-no',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'6-start',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'6-why',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'6-1-fine',rewind:'6-1-fine-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'6-2-no',rewind:'6-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'6-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'6-howlong',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'6-1-fine',rewind:'6-1-fine-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'6-2-no',rewind:'6-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
      ]
    },
    {
     base:{
      src:'6-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:'6-yes',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'6-2-no',rewind:'6-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
      ]
    },
    {
     base:{
      src:'7-start',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'7-3-why',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'7-1-boom',rewind:'7-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'7-2-no',rewind:'7-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
     ]
    },
    {
     base:{
      src:'7-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
	  {src:'7-3-3-docs',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}},
      {src:'7-1-boom',rewind:'7-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'7-2-no',rewind:'7-2-no-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}}
      ]
    },
    {
     base:{
      src:'7-int',
      timecodes:[],
      end:{data:{interactive:'UPop',conf:{cls:'choose'}}}
     },
     choose:[
      {src:'7-3-3-1-boom',rewind:'7-3-3-1-boom-rev',data:{interactive:'UPop',conf:{correct:false,cls:'info'}}},
      {src:'7-3-3-2-no',data:{interactive:'UPop',conf:{correct:true,cls:'info'}}}
     ]
    }
   ]
  }
 },
 interactives:{

 }
};