export const data={
 timecodes:[],
 touchPlayRadius:20,
 testSpeedFile:'images/dl-speed.jpg',
 redirect:'',
 _production:false,
 quality:{},
 events:{
  'iiBack':'.int-ind-back'
 },
 view:{
  el:'.video-js',
  goOn:'.continue',
  extTemplate:'#ext-player-template',
  $btns:'.special-btns',
  $smooth:'.smooth',
  shownCls:'shown'
 }
};