export const data={
 btnBack:0,
 timecodes:[],
 touchPlayRadius:20,
 testSpeedFile:'images/dl-speed.jpg',
 redirect:'',
 _production:false,
 quality:{},
 events:{
  'jBack':'.just-back',
  'iBack':'.int-back',
  'iiBack':'.int-ind-back'
 },
 view:{
  el:'.video-js',
  goOn:'.continue',
  extTemplate:'#ext-player-template'
 }
};